name: bitrise-step-integration-test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ main, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bitrise-step-integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Call Bitrise API
        env:
          BITRISE_API_TOKEN: ${{ secrets.BITRISE_API_TOKEN }}
          BITRISE_SLUG_ID: ${{ secrets.BITRISE_SLUG_ID }}
          BITRISE_WORKFLOW_ID: ${{ secrets.BITRISE_WORKFLOW_ID }}
        run: |
          COMMIT_HASH=`git rev-parse HEAD`
          curl https://app.bitrise.io/app/${BITRISE_SLUG_ID}/build/start.json --data '{"hook_info":{"type":"bitrise","build_trigger_token":"${BITRISE_API_TOKEN}"},"build_params":{"branch":"main","workflow_id":"${BITRISE_WORKFLOW_ID}","environments":[{"mapped_to":"AUTIFY_MOBILE_SCRIPT_BRANCH","value":"${GITHUB_HEAD_REF}","is_expand":true}]},"triggered_by":"curl"}'
